spring:
  datasource:
    url: jdbc:mysql://sql./jiandan_house?characterEncoding=utf-8&useSSL=false
    username:
    password: @
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update

mail:
  delevop_id:
  templet_code:
  account:
  password: